### ISSUE TITLE
gulp dist | error no 'bower-assets-dist'

### ISSUE THREAD

**Issue by AquilaSagitta** [reflexdemon/slush-angular-gulp#12]
gulp dist is broken on fresh scaffold.

**Comment by reflexdemon** [comment]
let me check on it. Cos, I remember fixing this a while a go.

**Comment by reflexdemon** [comment]
Fixed part of `slush-angular-gulp@0.2.8`.

**Comment by AquilaSagitta** [comment]
did you try running `gulp dist` ? Its still throwing `[07:38:42] Task 'bower-assets-dist' is not in your gulpfile` for me.
By the way... PR https://github.com/reflexdemon/slush-angular-gulp/issues/13 had nothing to do with this issue

**Comment by reflexdemon** [comment]
Will check on this.

**Comment by AquilaSagitta** [comment]
Check PR https://github.com/reflexdemon/slush-angular-gulp/pull/14 which fixes this issue.

**Comment by reflexdemon** [comment]
You rock.

**Comment by AquilaSagitta** [comment]
This may still have issues with templates not getting pipe'd over but haven't had time to test

**Comment by reflexdemon** [comment]
Can you please give me the error message if you have any stack trace.
I will see if I can fix it.

**Comment by AquilaSagitta** [comment]
Check PR https://github.com/reflexdemon/slush-angular-gulp/pull/15 should fix template issue
